"use client";
import Link from "next/link";
import { usePathname, useRouter } from "next/navigation";
import { Activity, CalendarDays, ChevronLeft, FileText, GalleryHorizontalEnd, LayoutDashboard, LogOut, Menu, MessageSquare, Radio, Settings, ShieldCheck, Users, Video, X } from "lucide-react";
import { useState } from "react";
import { getAllowedAdminMenu, type AdminRole } from "@/lib/permissions/rbac";
import { createClient } from "@/lib/supabase/client";
import { Logo } from "@/components/layout/logo";
import { NotificationMenu } from "@/components/admin/notification-menu";
import { cn } from "@/lib/utils";
const iconMap=[LayoutDashboard,CalendarDays,Activity,Video,Radio,FileText,Users,Users,GalleryHorizontalEnd,ShieldCheck,Users,MessageSquare,FileText,Users,Settings,Settings];
export function AdminSidebar({role="super_admin"}:{role?:AdminRole}){const path=usePathname();const router=useRouter();const[open,setOpen]=useState(false);const menus=getAllowedAdminMenu(role);async function logout(){try{await createClient().auth.signOut();}catch{}router.push("/auth/login");router.refresh();}return <><button onClick={()=>setOpen(true)} className="fixed left-4 top-4 z-40 grid size-11 place-items-center rounded-full bg-primary text-white lg:hidden" aria-label="Buka sidebar"><Menu/></button>{open&&<button className="fixed inset-0 z-40 bg-black/50 lg:hidden" onClick={()=>setOpen(false)} aria-label="Tutup sidebar"/>}<aside className={cn("fixed inset-y-0 left-0 z-50 flex w-72 flex-col bg-primary text-white transition-transform lg:translate-x-0",open?"translate-x-0":"-translate-x-full")}><div className="flex h-20 items-center justify-between border-b border-white/10 px-6"><Logo light/><div className="flex items-center gap-1"><NotificationMenu/><button onClick={()=>setOpen(false)} className="lg:hidden" aria-label="Tutup"><X/></button></div></div><div className="flex-1 overflow-y-auto p-4"><p className="px-3 py-3 text-[10px] font-bold uppercase tracking-[.2em] text-white/35">Administrasi</p><nav className="space-y-1">{menus.map((item,i)=>{const Icon=iconMap[i]??FileText;const active=path===item.href;return <Link key={item.href} href={item.href} onClick={()=>setOpen(false)} className={cn("flex min-h-11 items-center gap-3 rounded-xl px-3 text-sm text-white/65 transition hover:bg-white/8 hover:text-white",active&&"bg-gold text-primary hover:bg-gold hover:text-primary")}><Icon className="size-4"/>{item.label}</Link>;})}</nav></div><div className="border-t border-white/10 p-4"><Link href="/" className="flex min-h-11 items-center gap-3 rounded-xl px-3 text-sm text-white/65 hover:bg-white/8"><ChevronLeft className="size-4"/>Lihat Website</Link><button onClick={logout} className="flex min-h-11 w-full items-center gap-3 rounded-xl px-3 text-sm text-white/65 hover:bg-white/8"><LogOut className="size-4"/>Keluar</button></div></aside></>;}
