"use client";

import { FormEvent, useEffect, useState } from "react";
import { Loader2, MailPlus, RefreshCw, Save, ShieldCheck } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";

const roles = [["super_admin", "Super Admin"], ["web_administrator", "Web Administrator"], ["secretariat", "Sekretariat"], ["media_team", "Tim Media"], ["editor", "Editor"], ["pastoral", "Pastoral"], ["prayer_team", "Tim Doa"], ["department_admin", "Admin Departemen"]] as const;
type UserRow = { id: string; email: string; fullName: string; status: string; role: string | null; roleName: string | null; invitedAt: string | null; lastSignInAt: string | null; createdAt: string };
export function UserManager() {
  const [users, setUsers] = useState<UserRow[]>([]);
  const [loading, setLoading] = useState(true);
  const [saving, setSaving] = useState<string | null>(null);
  const [message, setMessage] = useState<string | null>(null);
  async function load() { setLoading(true); setMessage(null); const response = await fetch("/api/admin/users", { cache: "no-store" }); const result = await response.json().catch(() => ({})); if (response.ok) setUsers(result.data ?? []); else { setUsers([]); setMessage(result.message ?? "Pengguna tidak dapat dimuat"); } setLoading(false); }
  useEffect(() => { const timer = window.setTimeout(() => void load(), 0); return () => window.clearTimeout(timer); }, []);
  async function invite(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const formElement = event.currentTarget; setSaving("invite"); setMessage(null); const values = Object.fromEntries(new FormData(formElement)); const response = await fetch("/api/admin/users", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(values) }); const result = await response.json().catch(() => ({})); if (response.ok) { setUsers((current) => [result.data, ...current]); formElement.reset(); setMessage("Undangan admin berhasil dikirim."); } else setMessage(result.message ?? "Undangan gagal"); setSaving(null); }
  async function update(user: UserRow, values: { role?: string; status?: string }) { setSaving(user.id); setMessage(null); const response = await fetch(`/api/admin/users/${user.id}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify(values) }); const result = await response.json().catch(() => ({})); if (response.ok) { setUsers((current) => current.map((item) => item.id === user.id ? { ...item, ...values } : item)); setMessage("Pengguna berhasil diperbarui."); } else setMessage(result.message ?? "Perubahan gagal"); setSaving(null); }
  return <div className="space-y-5"><form onSubmit={invite} className="grid gap-4 rounded-2xl border border-primary/10 bg-white p-5 lg:grid-cols-[1fr_1fr_220px_auto] lg:items-end"><label className="text-sm font-semibold text-primary">Nama lengkap<Input name="fullName" required minLength={2} className="mt-2 bg-cream" /></label><label className="text-sm font-semibold text-primary">Email<Input name="email" type="email" required className="mt-2 bg-cream" /></label><label className="text-sm font-semibold text-primary">Role<select name="role" required className="mt-2 h-12 w-full rounded-xl border border-primary/15 bg-cream px-3">{roles.map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></label><Button disabled={saving === "invite"}>{saving === "invite" ? <Loader2 className="size-4 animate-spin" /> : <MailPlus className="size-4" />}Kirim Undangan</Button></form>
    {message && <div role="status" className="rounded-xl border border-amber-200 bg-amber-50 p-4 text-sm text-amber-900">{message}</div>}
    <div className="overflow-hidden rounded-2xl border border-primary/10 bg-white"><div className="flex items-center justify-between border-b border-primary/10 p-5"><div><h2 className="font-serif text-2xl text-primary">Akun Admin</h2><p className="text-xs text-muted">{users.length} akun pada halaman ini</p></div><Button variant="secondary" size="icon" onClick={() => void load()} aria-label="Muat ulang"><RefreshCw className={`size-4 ${loading ? "animate-spin" : ""}`} /></Button></div><div className="overflow-x-auto"><table className="w-full min-w-[850px] text-left"><thead className="bg-cream text-[11px] uppercase tracking-wider text-muted"><tr><th className="px-5 py-4">Pengguna</th><th className="px-5 py-4">Role</th><th className="px-5 py-4">Status</th><th className="px-5 py-4">Login Terakhir</th><th className="px-5 py-4">Aksi</th></tr></thead><tbody className="divide-y divide-primary/8">{loading ? <tr><td colSpan={5} className="p-10 text-center"><Loader2 className="mx-auto size-5 animate-spin text-secondary" /></td></tr> : users.length === 0 ? <tr><td colSpan={5} className="p-10 text-center text-sm text-muted">Belum ada data pengguna atau Supabase belum dikonfigurasi.</td></tr> : users.map((user) => <UserRowEditor key={user.id} user={user} saving={saving === user.id} onSave={(values) => void update(user, values)} />)}</tbody></table></div></div>
  </div>;
}
function UserRowEditor({ user, saving, onSave }: { user: UserRow; saving: boolean; onSave: (values: { role: string; status: string }) => void }) {
  const [role, setRole] = useState(user.role ?? "editor"); const [status, setStatus] = useState(user.status);
  return <tr><td className="px-5 py-4"><div className="flex items-center gap-3"><span className="grid size-10 place-items-center rounded-full bg-cream text-secondary"><ShieldCheck className="size-4" /></span><div><p className="font-semibold text-primary">{user.fullName || "Tanpa nama"}</p><p className="text-xs text-muted">{user.email}</p></div></div></td><td className="px-5 py-4"><select value={role} onChange={(event) => setRole(event.target.value)} className="h-10 rounded-lg border border-primary/15 px-2 text-sm">{roles.map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></td><td className="px-5 py-4"><select value={status} onChange={(event) => setStatus(event.target.value)} className="h-10 rounded-lg border border-primary/15 px-2 text-sm"><option value="active">Aktif</option><option value="inactive">Nonaktif</option></select></td><td className="px-5 py-4 text-xs text-muted">{user.lastSignInAt ? new Date(user.lastSignInAt).toLocaleString("id-ID") : "Belum pernah"}</td><td className="px-5 py-4"><Button className="h-9" variant="secondary" disabled={saving || (role === user.role && status === user.status)} onClick={() => onSave({ role, status })}>{saving ? <Loader2 className="size-4 animate-spin" /> : <Save className="size-4" />}Simpan</Button></td></tr>;
}
