import type { Metadata } from "next";
import { Baby, Car, CircleHelp, MapPin, Shirt } from "lucide-react";
import { PageHero } from "@/components/sections/page-hero";
import { VisitorForm } from "@/components/forms/public-forms";
import { SectionHeading } from "@/components/sections/section-heading";

export const metadata: Metadata = { title: "Pengunjung Baru", description: "Panduan dan formulir rencana kunjungan pertama ke GMAHK Jemaat Naripan.", alternates: { canonical: "/pengunjung-baru" } };
const info=[{icon:MapPin,title:"Saat Anda tiba",text:"Tim penyambut membantu menemukan ruang ibadah dan informasi yang Anda perlukan."},{icon:Car,title:"Parkir",text:"Informasi area parkir resmi akan diperbarui setelah data lokasi dikonfirmasi."},{icon:Shirt,title:"Pakaian",text:"Tidak ada tuntutan berpakaian tertentu. Datanglah dengan pakaian yang nyaman dan sopan."},{icon:Baby,title:"Bersama anak",text:"Anak-anak diterima dengan sukacita dan tersedia kegiatan sesuai kelompok usia."}];
export default function VisitorPage(){ return <><PageHero eyebrow="Selamat Datang" title="Kunjungan pertama Anda" description="Kami ingin membantu Anda merasa tenang, diterima, dan mengetahui apa yang akan dijumpai." /><section className="section-pad bg-white"><div className="container-site"><SectionHeading eyebrow="Yang Perlu Diketahui" title="Datanglah sebagaimana adanya" description="Ibadah berlangsung hangat, tertib, dan berpusat pada Firman Tuhan." /><div className="mt-12 grid gap-5 sm:grid-cols-2 lg:grid-cols-4">{info.map(({icon:Icon,title,text})=><div key={title} className="rounded-2xl bg-cream p-6"><Icon className="text-gold" /><h2 className="mt-5 font-serif text-2xl text-primary">{title}</h2><p className="mt-3 text-sm leading-6 text-muted">{text}</p></div>)}</div></div></section><section className="section-pad bg-cream"><div className="container-site grid gap-10 lg:grid-cols-[.7fr_1.3fr]"><div><SectionHeading eyebrow="Rencanakan Kunjungan" title="Kami siap menyambut Anda" /><div className="mt-7 rounded-2xl bg-primary p-6 text-white"><p className="text-xs font-bold uppercase tracking-wider text-gold">Jadwal Utama</p><p className="mt-3 font-serif text-2xl">Kebaktian Sabat</p><p className="mt-2 text-sm text-white/60">Setiap Sabtu · 09.00 WIB</p></div></div><div className="rounded-2xl border border-primary/10 bg-white p-6 sm:p-10"><VisitorForm /></div></div></section><section className="section-pad bg-white"><div className="container-site max-w-4xl"><div className="flex items-center gap-3"><CircleHelp className="text-gold" /><h2 className="font-serif text-4xl text-primary">Pertanyaan yang sering ditanyakan</h2></div><div className="mt-8 divide-y divide-primary/10">{[["Apakah saya harus menjadi anggota untuk hadir?","Tidak. Siapa pun dipersilakan hadir dan beribadah bersama."],["Berapa lama ibadah berlangsung?","Ibadah Sabat berlangsung setiap Sabtu pukul 09.00–12.00 WIB."],["Apakah tersedia kontak penyambut?","Ya. Isi formulir kunjungan dan tim penyambut akan menghubungi Anda."]].map(([q,a])=><details key={q} className="group py-5"><summary className="cursor-pointer list-none font-semibold text-primary">{q}</summary><p className="mt-3 text-sm leading-6 text-muted">{a}</p></details>)}</div></div></section></>; }
