-- Harden content authorization and add database-level audit logging.

-- Remove the temporary broad dashboard-based policies from the initial migration.
do $$
declare t text;
begin
  foreach t in array array['site_settings','navigation_items','church_profiles','media_files','speakers','leaders','ministries','service_schedules','events','sermon_categories','sermons','post_categories','post_tags','posts','post_tag_assignments','livestreams','gallery_albums','gallery_images','announcements','downloads'] loop
    execute format('drop policy if exists "authenticated manage %s" on public.%I', t, t);
  end loop;
end $$;

-- Module-specific policies enforce least privilege even if an API check is bypassed.
create policy "public read public settings" on public.site_settings for select using (is_public and status = 'active');
do $$
declare item text[];
begin
  foreach item slice 1 in array array[
    array['site_settings','settings.manage'], array['navigation_items','appearance.manage'], array['church_profiles','settings.manage'],
    array['media_files','files.manage'], array['speakers','sermons.manage'], array['leaders','leaders.manage'],
    array['ministries','ministries.manage'], array['service_schedules','schedules.manage'], array['events','events.manage'],
    array['sermon_categories','sermons.manage'], array['sermons','sermons.manage'], array['post_categories','posts.manage'],
    array['post_tags','posts.manage'], array['post_tag_assignments','posts.manage'], array['posts','posts.manage'],
    array['livestreams','livestreams.manage'], array['gallery_albums','gallery.manage'], array['gallery_images','gallery.manage'],
    array['announcements','appearance.manage'], array['downloads','files.manage']
  ] loop
    execute format(
      'create policy "module manage %s" on public.%I for all to authenticated using (public.has_permission(%L)) with check (public.has_permission(%L))',
      item[1], item[1], item[2], item[2]
    );
  end loop;
end $$;

create policy "user administrators manage profiles" on public.profiles for all to authenticated
  using (public.has_permission('users.manage')) with check (public.has_permission('users.manage'));
create policy "user administrators manage assignments" on public.user_roles for all to authenticated
  using (public.has_permission('users.manage')) with check (public.has_permission('users.manage'));
create policy "user administrators read roles" on public.roles for select to authenticated using (public.has_permission('users.manage'));
create policy "user administrators read permissions" on public.permissions for select to authenticated using (public.has_permission('users.manage'));
create policy "user administrators read role permissions" on public.role_permissions for select to authenticated using (public.has_permission('users.manage'));

-- Audit records are append-only and generated by triggers, not trusted client payloads.
create or replace function public.audit_row_change() returns trigger
language plpgsql security definer set search_path = public as $$
begin
  insert into public.audit_logs(actor_id, action, entity_type, entity_id, old_data, new_data)
  values (
    auth.uid(), lower(tg_op), tg_table_name,
    coalesce((case when tg_op = 'DELETE' then old.id else new.id end), null),
    case when tg_op in ('UPDATE','DELETE') then to_jsonb(old) else null end,
    case when tg_op in ('INSERT','UPDATE') then to_jsonb(new) else null end
  );
  return case when tg_op = 'DELETE' then old else new end;
end;
$$;
revoke all on function public.audit_row_change() from public;

do $$
declare t text;
begin
  foreach t in array array['site_settings','navigation_items','church_profiles','media_files','speakers','leaders','ministries','service_schedules','events','sermon_categories','sermons','post_categories','post_tags','posts','livestreams','gallery_albums','gallery_images','announcements','downloads','prayer_requests','visitor_forms','contact_messages','event_registrations'] loop
    execute format('create trigger audit_%I after insert or update or delete on public.%I for each row execute function public.audit_row_change()', t, t);
  end loop;
end $$;

-- Audit logs cannot be modified through the Data API.
revoke insert, update, delete on public.audit_logs from anon, authenticated;
